/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sjeaohifojfjzxyodxhn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZWFvaGlmb2pmanp4eW9keGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MjEyODAsImV4cCI6MjA4ODM5NzI4MH0.EI1Gal-A0iTjC-o--BfYysWPYHDo0dY7iZVaET-nMCI"